export const BADGES = [
  // Welcome
  {
    id: 'critic_welcome',
    category: 'Welcome',
    name: 'The Critic',
    desc: 'Joined the Music Critics family. Welcome aboard!',
    emoji: '🎖️',
    color: '#a78bfa',
    glow: 'rgba(167,139,250,0.7)',
  },
  // Listening time — periodic
  {
    id: 'daily_listener',
    category: 'Listening Time',
    name: 'Daily Listener',
    desc: '45+ minutes on the app in a single day',
    emoji: '🌅',
    color: '#fbbf24',
    glow: 'rgba(251,191,36,0.6)',
  },
  {
    id: 'weekly_devotee',
    category: 'Listening Time',
    name: 'Weekly Devotee',
    desc: '3+ hours on the app in a single week',
    emoji: '🎧',
    color: '#f97316',
    glow: 'rgba(249,115,22,0.6)',
  },
  {
    id: 'monthly_obsessive',
    category: 'Listening Time',
    name: 'Monthly Obsessive',
    desc: '30+ hours on the app in a single month',
    emoji: '🔥',
    color: '#ef4444',
    glow: 'rgba(239,68,68,0.6)',
  },
  // Listening time — total
  {
    id: 'time_10h',
    category: 'Listening Time',
    name: 'Decade Listener',
    desc: '10+ total hours on the app',
    emoji: '⏱️',
    color: '#34d399',
    glow: 'rgba(52,211,153,0.6)',
  },
  {
    id: 'time_100h',
    category: 'Listening Time',
    name: 'Century Listener',
    desc: '100+ total hours on the app',
    emoji: '⌛',
    color: '#06b6d4',
    glow: 'rgba(6,182,212,0.6)',
  },
  {
    id: 'time_1000h',
    category: 'Listening Time',
    name: 'Millennium Listener',
    desc: '1,000+ total hours on the app',
    emoji: '🕰️',
    color: '#8b5cf6',
    glow: 'rgba(139,92,246,0.6)',
  },
  // Quality — likes received
  {
    id: 'likes_100',
    category: 'Quality',
    name: 'Rising Star',
    desc: '100+ total likes received on your reviews',
    emoji: '⭐',
    color: '#fbbf24',
    glow: 'rgba(251,191,36,0.6)',
  },
  {
    id: 'likes_300',
    category: 'Quality',
    name: 'Crowd Favorite',
    desc: '300+ total likes received on your reviews',
    emoji: '🌟',
    color: '#f59e0b',
    glow: 'rgba(245,158,11,0.6)',
  },
  {
    id: 'likes_500',
    category: 'Quality',
    name: 'Legend',
    desc: '500+ total likes received on your reviews',
    emoji: '💫',
    color: '#d97706',
    glow: 'rgba(217,119,6,0.6)',
  },
  // Community — comments received
  {
    id: 'comments_10',
    category: 'Community',
    name: 'Conversationalist',
    desc: '10+ comments received on your reviews',
    emoji: '💬',
    color: '#60a5fa',
    glow: 'rgba(96,165,250,0.6)',
  },
  {
    id: 'comments_50',
    category: 'Community',
    name: 'Community Pillar',
    desc: '50+ comments received on your reviews',
    emoji: '🗣️',
    color: '#3b82f6',
    glow: 'rgba(59,130,246,0.6)',
  },
  {
    id: 'comments_100',
    category: 'Community',
    name: 'Voice of the People',
    desc: '100+ comments received on your reviews',
    emoji: '📢',
    color: '#2563eb',
    glow: 'rgba(37,99,235,0.6)',
  },
  {
    id: 'comments_200',
    category: 'Community',
    name: 'Icon',
    desc: '200+ comments received on your reviews',
    emoji: '👑',
    color: '#7c3aed',
    glow: 'rgba(124,58,237,0.6)',
  },
];

export const BADGE_MAP = Object.fromEntries(BADGES.map(b => [b.id, b]));
export const BADGE_CATEGORIES = ['Welcome', 'Listening Time', 'Quality', 'Community'];