export const GENRES = [
  { id: 'rock',       label: 'Rock',       entityGenre: 'rock',       icon: '🎸', tagline: 'Underground · Raw · Alive',               desc: 'The sound of rebellion, garage riffs, and honest power.' },
  { id: 'pop',        label: 'Pop',        entityGenre: 'pop',        icon: '🎤', tagline: 'Clean · Bright · Now',                    desc: 'Hooks that last forever. Perfectly polished moments.' },
  { id: 'classical',  label: 'Classical',  entityGenre: 'classical',  icon: '🎻', tagline: 'Timeless · Precise · Profound',            desc: 'Centuries of craft distilled into structured beauty.' },
  { id: 'metal',      label: 'Metal',      entityGenre: 'metal',      icon: '🤘', tagline: 'Heavy · Dark · Relentless',               desc: 'Pure intensity. No compromise. Total commitment.' },
  { id: 'jazz',       label: 'Jazz',       entityGenre: 'jazz',       icon: '🎷', tagline: 'Improvised · Intimate · Late Night',       desc: 'Where conversation becomes music. Every note a deliberate choice.' },
  { id: 'blues',      label: 'Blues',      entityGenre: null,         icon: '🎺', tagline: 'Slow · Honest · Deep',                    desc: 'The roots of everything. Pain turned into beauty.' },
  { id: 'r_and_b',    label: 'R&B',        entityGenre: 'r_and_b',    icon: '🎙️', tagline: 'Smooth · Soulful · Night',                desc: 'Rhythm, soul, and the warmth of 2am.' },
  { id: 'hardcore',   label: 'Hardcore',   entityGenre: 'punk',       icon: '💢', tagline: 'Fast · Loud · No Filler',                 desc: 'Zero pretense. Maximum energy. Pure.' },
  { id: 'country',    label: 'Country',    entityGenre: 'country',    icon: '🤠', tagline: 'Warm · Story-driven · Real',              desc: 'Life, roads, and the people you never forget.' },
  { id: 'hip_hop',    label: 'Hip-hop',    entityGenre: 'hip_hop',    icon: '🎧', tagline: 'Culture · Rhythm · Truth',                desc: 'A whole culture compressed into beats and bars.' },
  { id: 'indie',      label: 'Indie',      entityGenre: 'indie',      icon: '🌿', tagline: 'Curious · Unfiltered · Yours',            desc: 'Made on your own terms. Nothing to prove.' },
  { id: 'grunge',     label: 'Grunge',     entityGenre: null,         icon: '📻', tagline: 'Distorted · Raw · Unapologetic',          desc: 'Flannel, feedback, and feelings too big to name.' },
  { id: 'electronic', label: 'Electronic', entityGenre: 'electronic', icon: '⚡', tagline: 'Synthetic · Future · Dance',              desc: 'Sound as architecture. The machine with a soul.' },
];

export const genreThemes = {
  default: {
    wrapper: {},
    card: { background: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: '12px', color: 'hsl(var(--card-foreground))' },
    text: {},
    muted: 'hsl(var(--muted-foreground))',
    accent: 'hsl(var(--primary))',
    hoverEffect: 'lift',
  },
  rock: {
    wrapper: { background: 'linear-gradient(160deg,#1c1c1c 0%,#101010 100%)', color: '#e5e5e5', padding: '20px', borderRadius: '10px', marginTop: '6px' },
    card: { background: '#232323', border: '1px solid #363636', borderRadius: '5px', color: '#e5e5e5' },
    text: { fontWeight: 800, letterSpacing: '-0.03em' },
    muted: '#888',
    accent: '#e63946',
    hoverEffect: 'shake',
  },
  pop: {
    wrapper: { background: 'linear-gradient(160deg,#fff5f8 0%,#fef0f5 100%)', color: '#1a1a1a', padding: '20px', borderRadius: '16px', marginTop: '6px' },
    card: { background: '#fff', border: '1px solid #fce4ec', borderRadius: '18px', color: '#1a1a1a', boxShadow: '0 2px 16px rgba(236,64,122,0.07)' },
    text: { fontWeight: 500 },
    muted: '#c07090',
    accent: '#ec407a',
    hoverEffect: 'lift',
  },
  classical: {
    wrapper: { background: 'linear-gradient(160deg,#faf8f3 0%,#f2ead8 100%)', color: '#2a2218', padding: '20px', borderRadius: '4px', marginTop: '6px' },
    card: { background: '#fffef9', border: '1px solid #e5d9c0', borderRadius: '3px', color: '#2a2218' },
    text: { fontFamily: 'Georgia, serif', fontWeight: 500, letterSpacing: '0.01em' },
    muted: '#8a7a60',
    accent: '#8b6914',
    hoverEffect: 'none',
  },
  metal: {
    wrapper: { background: 'linear-gradient(160deg,#080808 0%,#050505 100%)', color: '#e0e0e0', padding: '20px', borderRadius: '2px', marginTop: '6px' },
    card: { background: '#101010', border: '1px solid #252525', borderRadius: '1px', color: '#e0e0e0' },
    text: { fontWeight: 900, letterSpacing: '-0.04em', textTransform: 'uppercase' },
    muted: '#666',
    accent: '#cc1111',
    hoverEffect: 'glow-red',
  },
  jazz: {
    wrapper: { background: 'linear-gradient(160deg,#0e1a2e 0%,#1a2a40 100%)', color: '#d4c5a9', padding: '20px', borderRadius: '10px', marginTop: '6px' },
    card: { background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(212,197,169,0.15)', borderRadius: '8px', color: '#d4c5a9', backdropFilter: 'blur(8px)' },
    text: { fontFamily: 'Georgia, serif', fontWeight: 400, letterSpacing: '0.02em' },
    muted: '#8a7a66',
    accent: '#d4a017',
    hoverEffect: 'glow-warm',
  },
  blues: {
    wrapper: { background: 'linear-gradient(160deg,#1a1f2e 0%,#141824 100%)', color: '#b0bec5', padding: '20px', borderRadius: '8px', marginTop: '6px' },
    card: { background: '#1e2432', border: '1px solid #2a3040', borderRadius: '6px', color: '#b0bec5' },
    text: { fontWeight: 400, letterSpacing: '0.01em' },
    muted: '#607080',
    accent: '#5c8ab5',
    hoverEffect: 'lift',
  },
  r_and_b: {
    wrapper: { background: 'linear-gradient(160deg,#1a0a2e 0%,#0f0818 100%)', color: '#e0d0f0', padding: '20px', borderRadius: '12px', marginTop: '6px' },
    card: { background: 'rgba(120,60,180,0.12)', border: '1px solid rgba(180,120,255,0.18)', borderRadius: '12px', color: '#e0d0f0', backdropFilter: 'blur(8px)' },
    text: { fontWeight: 400, letterSpacing: '0.01em' },
    muted: '#9070b0',
    accent: '#b47fff',
    hoverEffect: 'glow-purple',
  },
  hardcore: {
    wrapper: { background: '#000', color: '#f0f0f0', padding: '20px', borderRadius: '0px', marginTop: '6px' },
    card: { background: '#0a0a0a', border: '1px solid #1e1e1e', borderRadius: '0px', color: '#f0f0f0' },
    text: { fontWeight: 900, letterSpacing: '-0.05em', textTransform: 'uppercase' },
    muted: '#606060',
    accent: '#ffffff',
    hoverEffect: 'instant',
  },
  country: {
    wrapper: { background: 'linear-gradient(160deg,#fdf6e3 0%,#f5ead0 100%)', color: '#3a2e1a', padding: '20px', borderRadius: '8px', marginTop: '6px' },
    card: { background: '#fefaf0', border: '1px solid #e8d9b8', borderRadius: '8px', color: '#3a2e1a' },
    text: { fontWeight: 500 },
    muted: '#8a7a5a',
    accent: '#a0522d',
    hoverEffect: 'lift',
  },
  hip_hop: {
    wrapper: { background: 'linear-gradient(160deg,#0a0a0a 0%,#111 100%)', color: '#f0f0f0', padding: '20px', borderRadius: '4px', marginTop: '6px' },
    card: { background: '#161616', border: '1px solid #2c2c2c', borderRadius: '4px', color: '#f0f0f0' },
    text: { fontWeight: 800, letterSpacing: '-0.02em' },
    muted: '#888',
    accent: '#f5c518',
    hoverEffect: 'scale',
  },
  indie: {
    wrapper: { background: 'linear-gradient(160deg,#f7f5f2 0%,#eeebe4 100%)', color: '#2a2a2a', padding: '20px', borderRadius: '10px', marginTop: '6px' },
    card: { background: '#fafaf7', border: '1px solid #dddad3', borderRadius: '10px', color: '#2a2a2a' },
    text: { fontWeight: 400, letterSpacing: '0.01em' },
    muted: '#888880',
    accent: '#7a8a6a',
    hoverEffect: 'lift',
  },
  grunge: {
    wrapper: { background: 'linear-gradient(160deg,#1c1810 0%,#130f08 100%)', color: '#c8b89a', padding: '20px', borderRadius: '4px', marginTop: '6px' },
    card: { background: '#201c14', border: '1px solid #3a3028', borderRadius: '4px', color: '#c8b89a' },
    text: { fontWeight: 600, letterSpacing: '-0.01em' },
    muted: '#80706a',
    accent: '#8b7355',
    hoverEffect: 'lift',
  },
  electronic: {
    wrapper: { background: 'linear-gradient(160deg,#050a1a 0%,#0a0f22 100%)', color: '#c8d8f0', padding: '20px', borderRadius: '8px', marginTop: '6px' },
    card: { background: 'rgba(20,50,120,0.35)', border: '1px solid rgba(80,140,255,0.22)', borderRadius: '8px', color: '#c8d8f0', backdropFilter: 'blur(8px)' },
    text: { fontWeight: 500, letterSpacing: '0.04em' },
    muted: '#5080a0',
    accent: '#4080ff',
    hoverEffect: 'glow-blue',
  },
};