const keys = ['edit','edited','save','saving','cancel','title','content','rating','band_style','band_background','band_history','band_story','genre','hero_image_url','picks','artist','cover_url','blurb','add','remove','pending','failed','missing','conflict'];
const rows = {
  en: ['Edit review','Edited','Save changes','Checking and saving…','Cancel','Title','Review','Rating (1–5)','Style','Band background','Band history','Album background','Genre','Cover image URL','Album picks','Artist','Cover URL','Commentary','Add album','Remove','Awaiting approval','Could not save. Please try again.','Album removed','This review changed elsewhere. Reopen the editor.'],
  zh: ['编辑乐评','修改于','保存修改','审核并保存中…','取消','标题','正文','评分（1–5）','风格','乐队背景','乐队历史','专辑背景','流派','封面图片链接','推荐专辑','艺人','封面链接','评述','添加专辑','移除','等待审核','保存失败，请重试。','专辑已删除','乐评已在其他地方修改，请重新打开编辑器。'],
  ja: ['レビューを編集','編集日時','変更を保存','確認・保存中…','キャンセル','タイトル','本文','評価（1–5）','スタイル','バンド背景','バンドの歴史','アルバム背景','ジャンル','表紙画像URL','選んだアルバム','アーティスト','画像URL','解説','アルバム追加','削除','承認待ち','保存できませんでした。再試行してください。','アルバム削除済み','レビューが更新されました。編集画面を開き直してください。'],
  ko: ['리뷰 수정','수정일','변경 저장','검토 및 저장 중…','취소','제목','본문','평점 (1–5)','스타일','밴드 배경','밴드 역사','앨범 배경','장르','표지 이미지 URL','추천 앨범','아티스트','표지 URL','해설','앨범 추가','삭제','승인 대기','저장하지 못했습니다. 다시 시도하세요.','삭제된 앨범','리뷰가 변경되었습니다. 편집기를 다시 여세요.'],
  fr: ['Modifier la critique','Modifié le','Enregistrer','Vérification et enregistrement…','Annuler','Titre','Texte','Note (1–5)','Style','Contexte du groupe','Histoire du groupe','Contexte de l’album','Genre','URL de couverture','Sélection d’albums','Artiste','URL de couverture','Commentaire','Ajouter un album','Retirer','En attente de validation','Échec de sauvegarde. Réessayez.','Album supprimé','La critique a changé. Rouvrez l’éditeur.'],
  ru: ['Изменить рецензию','Изменено','Сохранить','Проверка и сохранение…','Отмена','Заголовок','Текст','Оценка (1–5)','Стиль','О группе','История группы','Об альбоме','Жанр','URL обложки','Подборка альбомов','Исполнитель','URL обложки','Комментарий','Добавить альбом','Удалить','Ожидает проверки','Не удалось сохранить. Повторите попытку.','Альбом удалён','Рецензия изменилась. Откройте редактор снова.'],
};
export default function editCopy(lang) { return Object.fromEntries(keys.map((k, i) => [k, (rows[lang] || rows.en)[i]])); }